version: "1.0"
networks:
  sql_rest:
    name: sql_rest
    driver: bridge
volumes:
  mysql-data:
    driver: local
services:
  mysql_host:
    image: mysql:latest
    container_name: mysql_host
    environment:
      MYSQL_HOST: mysql_host
      MYSQL_DATABASE: ssh
      MYSQL_USER: sshuser
      MYSQL_PASSWORD: sshflydigits
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - sql_rest
  api:
    build: .
    ports:
      - "443:443"
    depends_on:
      - mysql_host
    networks:
      - sql_rest
  web:
    image: nginx:latest
    volumes:
      - ./src:/usr/share/nginx/html
    ports:
      - "443:443"
    networks:
      - sql_rest