version: '1.0'
networks:
  sql_rest:
    name: sql_rest
    driver: bridge
volumes:
  mysql-data:
    driver: local
services:
  mysql_host:
    image: mysql:latest
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: fermi
      MYSQL_DATABASE: scuola
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: fermi
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - sql_rest
  rest_api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql_host
    environment:
      - MYSQL_HOST=mysql_host
    networks:
      - sql_rest