version: '1.0'

# TEST DOCKER COMPOSE
networks:
  flydigit_network:
    name: flydigit_network
    driver: bridge
volumes:
  mysql-data:
    driver: local
services:
  website:
    image: flydigit:latest
    container_name: flydigit
    ports:
      - 443:443
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - flydigit_network